title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

plugins:
  - jekyll-seo-tag

url: https://just-the-docs.github.io

search_enabled: true

# Optional: color customization
color_scheme: dark  # light  dark or auto

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
# Optional: logo
# logo: "/assets/images/logo.png"
